name: distinct_value_connectable_stream
description: Distinct value connectable stream for RxDart, useful for BLoC pattern
version: 1.0.3
homepage: https://github.com/hoc081098/distinct_value_connectable_stream

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  rxdart: ^0.23.1
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.0.0
  mockito: ^3.0.0
