name: distinct_value_connectable_stream
description: Distinct value connectable stream for RxDart, useful for BLoC pattern
author: Petrus Nguyen Thai Hoc <hoc081098@gmail.com>
version: 1.2.0
homepage: https://github.com/hoc081098/distinct_value_connectable_stream.git
repository: https://github.com/hoc081098/distinct_value_connectable_stream.git
issue_tracker: https://github.com/hoc081098/distinct_value_connectable_stream/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart_ext: ^0.0.1
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
