name: distinct_value_connectable_stream
description: Distinct value connectable stream for RxDart, useful for BLoC pattern
version: 1.2.0-nullsafety.2
homepage: https://github.com/hoc081098/distinct_value_connectable_stream

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  rxdart_ext: ^0.0.1-nullsafety.2
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13

dependency_overrides:
  rxdart_ext:
    git:
      url: https://github.com/hoc081098/rxdart_ext.git
      ref: ce4dd9f7da007728cdf78a76aa9ebd12e36a3681
