name: distinct_value_connectable_observable
description: Distinct value connectable observable for RxDart, useful for BLoC pattern
version: 2.0.4-dev
homepage: https://github.com/hoc081098/distinct_value_connectable_observable
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  rxdart: ^0.23.0-dev.2
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: ^3.0.0
